name: Pytest

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Add this to enable manual triggers

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Submit results
      if: always()
      run: |
        pip install testit-cli
        export TMS_TOKEN=ZWQ4M0Vnc3FFZ0t6VlY0QjRO
        testit autotests_filter \
          --url https://team-4y6k.testit.software \
          --configuration-id 0198d162-1544-744f-a04b-3276d36b9e56 \
          --testrun-id 3f91fb59-e8ec-4349-80a1-cb25832c7225 \
          --framework pytest \
          --disable-cert-validation \
          --output tmp/filter.txt
        pytest "$(cat tmp/filter.txt)" \
          --tmsConfigurationId=0198d162-1544-744f-a04b-3276d36b9e56 \
          --tmsProjectId=0198d162-1514-7157-a67d-82bd275ba589 \
          --tmsPrivateToken=ZWQ4M0Vnc3FFZ0t6VlY0QjRO \
          --tmsUrl=https://team-4y6k.testit.software \
          --tmsTestRunId=3f91fb59-e8ec-4349-80a1-cb25832c7225 \
          --tmsAdapterMode=1 \
          --tmsCertValidation=false \
          --testit
